### ISSUE TITLE
[Feat]: Real Debrid File Processing + Queue Cleaner Script

### ISSUE THREAD

**Issue by kirincorleone** [RandomNinjaAtk/docker-lidarr-extended#186]
Hi, this is my flow:

1. Lidarr Ext through Torrent Blackhole to Real Debrid Manager
2. Real Debrid Manager caches the torrent/ magnet on real debrid server and serves a direct download HTTP link to Aria2-Pro
3. Aria2-Pro downloads a RAR of the torrent files through HTTP link
4. Manual Extract RAR Archive once download is completed
5. Manual Cue Split based on whether downloaded file is a single flac/ ape file with a corresponding cue file
6. Manual Transcode from 24 bit flac/ ape/ other to flac > Delete/ keep files based on Match with beets/ mb Picard
7. Queue Cleaner Script - Currently turned off as the script was removing entire queue because real debrid manager/ aria 2 does not share progress with Lidarr and the downloaded file is a RAR. I would like the script to run after the above is completed.

Is it possible to automate Steps 4-7 based on a watch folder/ file condition? 
In the meanwhile, or if you decide not to, can you guide me to some resources that I can look into for this? 

[Real Debrid Manager](https://github.com/hyperbunny77/RealDebridManager)
[Aria2-Pro](https://github.com/P3TERX/Aria2-Pro-Docker)

**Comment by RandomNinjaAtk** [comment]
Everything your asking for would need to be added to the download client. 

Similar to how I’ve done it in sabnzbd-extended… However I’m fairly certain black hole configurations should be avoided because they are not recommended and have been removed from most of the arr apps. 

So you need to find a client that works with lidarr and can run a post processing script on download completion, similar to sabnzbd.

There is nothing to be done here in this container or scripts. You may want to open a discussion thread and others may be able to print you in a better direction.

**Comment by popeye2468** [comment]
just to comment on this 

https://github.com/rogerfar/rdt-client
