### ISSUE TITLE
[Bug]: progressing metadata with freyr

### ISSUE THREAD

**Issue by ciB89** [RandomNinjaAtk/docker-lidarr-extended#258]
**Describe the bug**

freyr finds the album/songs, but when trying to process the metadata I get the following error for each song, making the entire download a failure:
`(failed: Error downloading album art [An error occurred while processing the data through the with middleware tagged [progressBar]: ENXIO: no such device or address, open '/dev/tty'])`

I am using version 1.0.10

**Comment by RandomNinjaAtk** [comment]
I feel like the progress bar error can be ignored, that is likely caused by the fact that its not being run interactively and executed via script.

**Comment by ciB89** [comment]
> I feel like the progress bar error can be ignored, that is likely caused by the fact that its not being run interactively and executed via script.

But it does not seem to download anything although it finds the songs because of the missing metadata.

There seems to be an option to not use the progress bar as described [here](https://github.com/miraclx/freyr-js/issues/331#issuecomment-1295817514).

**Comment by RandomNinjaAtk** [comment]
I did not have any problems, other than the occasional track failing. So what your experiencing could be isolated to your particular configuration/geolocation or something else entirely. My recommendation would be that you try to use the app manually to see if you still get the same error. That way you eliminate the possibility of a script issue. 

If you can prove it's a problem with the script and it can be reproduced, then there is a possibility of resolving it. However, this is more likely something else which is beyond my control, and that means it may need to be fixed upstream, just like you opened the issue already with the project. 

There are too many variables at play and that's why it makes it difficult to figure out the problem and I won't bother to take any further measures until you can prove its a script issue and it can be reproduced on my end.

**Comment by RandomNinjaAtk** [comment]
Based on the commit you posted with the --no-bar flag, I have made that change because it's applicable to this script automation. However, I don't know if it will solve the problem and I have not tested it, so feel free to report back after you pull the latest update.

**Comment by ciB89** [comment]
It seems to have fixed the issue.

**Comment by RandomNinjaAtk** [comment]
Thanks for doing the investigation and pointing me into the right direction.
