### ISSUE TITLE
[Bug]: Existing songs are redownloaded

### ISSUE THREAD

**Issue by ImjuzCY** [RandomNinjaAtk/docker-lidarr-extended#49]
**Describe the bug**
I have imported the my Lidarr db from a vanilla Lidarr to lidarr-extended, so some songs are already downloaded and imported. However, the script seems to redownload and reimport the albums that are already in disk? I remember that amd had an environmental variable `DOWNLOADMODE`, if set to `wanted`, existing albums will not be downloaded. This environmental variable is missing in lidarr-extended.

**To Reproduce**
1. Import (copy) old Lidarr db to lidarr-extended with songs already imported
2. Run script
3. See logs where existing albums are redownloaded

**Expected behavior**
Existing albums should not be redownloaded

**Log Data**
-

**Docker Info:**
 - Docker Version: 20.10.17
 - Extended Script Version: 1.0.230

**Comment by RandomNinjaAtk** [comment]
This is not a bug, you should check your lidarr settings to make sure you have it configured correctly, it only searches for items in the missing and cutoff list. So your items that were previously downloaded must be in either of those lists to be searched by the script, which is a lidarr configuration issue or a general lidarr issue not related to the script because the script has no control over that.
