### ISSUE TITLE
Not downloading missing albums

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [RandomNinjaAtk/docker-lidarr-extended#53]
Hi there,
first of all thanks for making this! Such a great project!

After downloading a lot, it finally stopped, even though there are still a "few" albums in the missing and cutoff unmet lists.

This is what the log output says:

> 2022-08-18 21:09:05 :: Extended Audio :: FINDING MISSING ALBUMS :: sorted by date
> 2022-08-18 21:09:05 :: Extended Audio :: Downloading page 1... (0 - 500 of 1000 Results)
> 2022-08-18 21:09:10 :: Extended Audio :: Downloading page 2... (500 - 1000 of 1000 Results)
> 2022-08-18 21:09:15 :: Extended Audio :: Downloading page 3... (1000 - 1000 of 1000 Results)
> 2022-08-18 21:09:15 :: Extended Audio :: 0 MISSING ALBUMS FOUND
> 2022-08-18 21:09:16 :: Extended Audio :: FINDING CUTOFF ALBUMS sorted by date
> 2022-08-18 21:09:16 :: Extended Audio :: Downloading page 1... (0 - 500 of 600 Results)
> 2022-08-18 21:09:22 :: Extended Audio :: 0 CUTOFF ALBUMS FOUND
> 2022-08-18 21:09:22 :: Extended Audio :: Searching for 0 items
> 2022-08-18 21:09:22 :: Extended Audio :: No items to find, end

Shouldn't it be downloading those remaining 1600 albums?

sampling random albums manually, they do appear on deezer.

**Comment by RandomNinjaAtk** [comment]
No, this is by design. If you read all your logs. You’ll see it already searched for those and didn’t find them. So now it just skips stuff it already searched for to save time

**Comment by RandomNinjaAtk** [comment]
Look through the logs folder, there is a notfound folder and if you clear the contents it should retry. It will also should retry automatically after 90 days

**Comment by 1337sup3rh4x0r** [comment]
got it, thanks!

**Comment by j0hnskot** [comment]
I have the same issue and I just tried deleting the notfound folder. When I did,  I got a bunch of "Results found, but none matching search criteria..." error messages. What are those criteria and how can I review/change them?

**Comment by RandomNinjaAtk** [comment]
Albums on the service are rejected for 4 different reasons. That means either Track Count, Album Title, Lyric Type and First word didn't match up with any of the items on the service.

Possible reasons:

1. Album title is evaluated using this algorithm: https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance
If its greater than 5, its rejected.

2. Its rejected if there if the album doesn't have a track count less than equal to the maximum release track count or greater than equal to the lowest release track count for a release group.

3. If the first 3 letters of the album name on the service, doesn't match a musicbrainz release, it will be rejected.

4. If you don't have the lyric type set to both, then if the service album doesn't match your required type, it can also be rejected...

**Comment by berto0** [comment]
Thanks for the great work.

It would be possible to include the -e MatchDistance option to try to download missing albums.

Thank you

**Comment by krokenn** [comment]
"Its rejected if the service album doesn't have a track count less than equal to the maximum musicbrainz release track count or greater than equal to the lowest musicbrainz elease track count for a musicbrainz release group."

im trying to use matchdistance 20 but still some albums wont download and added to skiplist, i found out this is because im using deezer and for example when adding a new artist manually to lidarr it will add the albums but choose the best release candidate eg My Album (Deluxe) 22 Tracks but on deezer the My Album 12 can be found, not my question is probably related more to lidarr but i have over 100 albums that did not download because of this, is there a way to set the Release to be any? i mean what ever it find it will update in lidarr.

**Comment by RandomNinjaAtk** [comment]
You need to make sure musicbrainz has a matching album with the same title and track count. Then lidarr has to also have that information. So if its not on musicbrainz, you may need to add it as a release to the main release-group.

**Comment by krokenn** [comment]
> You need to make sure musicbrainz has a matching album with the same title and track count. Then lidarr has to also have that information. So if its not on musicbrainz, you may need to add it as a release to the main release-group.

Yes example both My Album (Deluxe) 22  and My Album 12 Tracks are listed on musicbrainz but only when i manually change the release candidate to My Album 12 Tracks in lidarr it will download it from deezer, else its added to skiplist and not downloaded..

1. Add artist to lidarr
2. Liddar scans the folder and finds both My Album (Deluxe) 22 Tracks and My Album 12 Tracks from musicbrainz, selecting default My Album (Deluxe) 22 as best release candidate.
3. Script begin searching album from deezer and finds only My Album 12 (My Album (Deluxe) 22  is not available on deezer and normally lidarr is seraching other source but we only use deezer right) instead of downloading its sent to notfound and its repeated for almost every artist i tried so far. 
5. Manually edit xxx albums and delete all files in notfound folder...

**Comment by RandomNinjaAtk** [comment]
Youll need to provide log output for when it searched and didn't find it.

It should find any release lidarr has stored for the release group based on the factors provided above. So there is no need to manually change the release in lidarr.
