### ISSUE TITLE
[Bug]: Clean name and name ambiguation

### ISSUE THREAD

**Issue by Kolbasz12** [RandomNinjaAtk/docker-lidarr-extended#98]
**Describe the bug**
Artist folde rname set to:
{Artist CleanName}

Suggested rename: 

Tiësto

Name ambiguation off, but folder artist suggested as:

Axwell Λ Ingrosso (2+3 of Swedish House Mafia)

**To Reproduce**
Artist folde rname set to:
{Artist CleanName}

**Expected behavior**
Tiesto
Axwell Λ Ingrosso

**Docker Info:**
 - Docker Version: 1.1.0.2649

**Additional context**
Tested same settings in base  (original) lidarr and the outputs appear as expected.

Not sure if it is a setting overwriting from the docker run, but the UI settings are not producing the expected output.

**Comment by RandomNinjaAtk** [comment]
If your using autoconfig, be sure you have disabled that to prevent your lidarr settings from being overwritten.

**Comment by Kolbasz12** [comment]
Is that as simple as setting it to false?  Changes it to false, docker restarted, but the behavior is the same.

**Comment by Kolbasz12** [comment]
OK, so it appears it may be an issue from initial import.

set clean name
Delete artist
search artist tiesto
artist found: Tiësto
set path: /music/

Tiësto added.  Path to Tiesto is /music/Tiësto, essentially ignoring the call for "clean name"

Happens in Lidarr (base) as well.  Will open a case with them,

**Comment by RandomNinjaAtk** [comment]
Yeah, this is essentially the same as the base image, so if its a problem here, its a problem there.... However, I think I may adjust the default optimized setting to use clean artist name...

**Comment by wouterverduin** [comment]
Hi! I would like to tune in on this; Since i run into exactly the same error.

Been breaking my head about it for over a week to narrow down this same bug. I installed the linuxserver/lidarr image yesterday and let it scan my exact same library and it runs fine.
However the lidarr-extended version (and maybe the develop branch?) is having this issue of after initial setup looking for artist (clean name) while my folders are just artist name.

Can i disable the setting overwrite in the docker-compose file to get this problem sorted or is it a problem with the lidarr develop branch?
Or is it possible to use another lidarr branch for lidarr extended? 

Would love the help since i am at my wits end :)

**Comment by RandomNinjaAtk** [comment]
Don't use the auto config feature and your settings will be left alone.
